# Generated by Django 6.0.4 on 2026-06-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_chain_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party_name',
            field=models.CharField(default='Independent', max_length=50),
        ),
    ]
